source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'

gem "wkhtmltopdf-binary"
gem "wicked_pdf"
gem 'tinymce-rails', git: 'https://github.com/spohlenz/tinymce-rails.git', branch: 'tinymce-4'

group :doc do
  gem 'sdoc', require: false
end

